# Generated by Django 5.2.7 on 2025-12-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caredac_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverInfo',
            fields=[
                ('caregiver_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='caregiver/profile_pics/')),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('acc_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'caregiver_info',
            },
        ),
        migrations.CreateModel(
            name='CaregiverDocuments',
            fields=[
                ('docx_id', models.AutoField(primary_key=True, serialize=False)),
                ('covid_19', models.FileField(blank=True, null=True, upload_to='caregiver/covid_19/')),
                ('first_aid', models.FileField(blank=True, null=True, upload_to='caregiver/first_aid/')),
                ('ndis', models.FileField(blank=True, null=True, upload_to='caregiver/ndis/')),
                ('police', models.FileField(blank=True, null=True, upload_to='caregiver/police/')),
                ('child_chk', models.FileField(blank=True, null=True, upload_to='caregiver/child_chk/')),
                ('visa', models.FileField(blank=True, null=True, upload_to='caregiver/visa/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='caregiver/resume/')),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, to='caregiver.caregiverinfo')),
            ],
            options={
                'db_table': 'caregiver_documents',
            },
        ),
        migrations.CreateModel(
            name='CaregiverDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.IntegerField(default=0)),
                ('disability_support_worker', models.IntegerField(default=0)),
                ('hours_cnt', models.IntegerField()),
                ('experience', models.CharField(max_length=255)),
                ('police_chk_status', models.CharField(max_length=255)),
                ('qualifications', models.TextField()),
                ('wcc', models.IntegerField(default=0)),
                ('ndis', models.IntegerField(default=0)),
                ('first_aid_training', models.IntegerField(default=0)),
                ('preferred_work_area', models.CharField(max_length=255)),
                ('services_offered', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, to='caregiver.caregiverinfo')),
            ],
            options={
                'db_table': 'caregiver_details',
            },
        ),
        migrations.CreateModel(
            name='CaregiverLanguage',
            fields=[
                ('caregiver_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('caregiver_id', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, to='caregiver.caregiverinfo')),
                ('language_id', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='caredac_admin.systemlanguage')),
            ],
            options={
                'db_table': 'caregiver_language',
            },
        ),
        migrations.CreateModel(
            name='CaregiverPayments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('set_primary', models.BooleanField(default=False)),
                ('caregiver_id', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, to='caregiver.caregiverinfo')),
            ],
            options={
                'db_table': 'caregiver_payments',
            },
        ),
    ]
