# Generated by Django 5.2.7 on 2025-11-25 07:06

import caregiver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverdocuments',
            name='child_chk',
            field=models.FileField(blank=True, null=True, upload_to=caregiver.models.child_chk_upload_to),
        ),
        migrations.AlterField(
            model_name='caregiverdocuments',
            name='covid_19',
            field=models.FileField(blank=True, null=True, upload_to=caregiver.models.covid_19_upload_to),
        ),
        migrations.AlterField(
            model_name='caregiverdocuments',
            name='first_aid',
            field=models.FileField(blank=True, null=True, upload_to=caregiver.models.first_aid_upload_to),
        ),
        migrations.AlterField(
            model_name='caregiverdocuments',
            name='ndis',
            field=models.FileField(blank=True, null=True, upload_to=caregiver.models.ndis_upload_to),
        ),
        migrations.AlterField(
            model_name='caregiverdocuments',
            name='police',
            field=models.FileField(blank=True, null=True, upload_to=caregiver.models.police_upload_to),
        ),
        migrations.AlterField(
            model_name='caregiverdocuments',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=caregiver.models.resume_upload_to),
        ),
        migrations.AlterField(
            model_name='caregiverdocuments',
            name='visa',
            field=models.FileField(blank=True, null=True, upload_to=caregiver.models.visa_upload_to),
        ),
    ]
