# Generated by Django 5.2.7 on 2025-11-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caredac_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('emergency_no', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('acc_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_master',
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('user_lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caredac_admin.systemlanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.usermaster')),
            ],
            options={
                'db_table': 'user_language',
            },
        ),
    ]
