# Generated by Django 5.2.7 on 2025-12-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caredac_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMaster',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'patient_master',
            },
        ),
        migrations.CreateModel(
            name='PatientLanguage',
            fields=[
                ('patient_language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='caredac_admin.systemlanguage')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
            options={
                'db_table': 'patient_language',
            },
        ),
        migrations.CreateModel(
            name='PatientHelp',
            fields=[
                ('patient_help_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
            options={
                'db_table': 'patient_help',
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.TextField()),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
            options={
                'db_table': 'patient_condition',
            },
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
                ('relation', models.CharField(choices=[('self', 'Self'), ('child', 'Child'), ('partner', 'Partner'), ('client', 'Client'), ('other', 'Other')], max_length=20)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
            options={
                'db_table': 'member_details',
            },
        ),
        migrations.CreateModel(
            name='PatientPayments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('set_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
            options={
                'db_table': 'patient_payments',
            },
        ),
        migrations.CreateModel(
            name='PatientService',
            fields=[
                ('patient_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('services', models.TextField()),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
            options={
                'db_table': 'patient_service',
            },
        ),
        migrations.CreateModel(
            name='SpecialNeeds',
            fields=[
                ('special_need_id', models.AutoField(primary_key=True, serialize=False)),
                ('needs', models.TextField()),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster')),
            ],
            options={
                'db_table': 'special_needs',
            },
        ),
    ]
