# Generated by Django 5.2.7 on 2025-12-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredac_admin', '0002_needhelp'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthelp',
            name='patient',
        ),
        migrations.AddField(
            model_name='patienthelp',
            name='help',
            field=models.ForeignKey(db_column='help_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='caredac_admin.needhelp'),
        ),
    ]
