# Generated by Django 5.2.7 on 2025-12-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patienthelp_patient_patienthelp_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthelp',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientmaster'),
        ),
    ]
