# Generated by Django 5.2.7 on 2025-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLanguage',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'system_language',
            },
        ),
    ]
