# Generated by Django 5.2.7 on 2025-12-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageOptions',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('languages_known', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'language_options',
            },
        ),
        # migrations.CreateModel(
        #     name='NeedHelp',
        #     fields=[
        #         ('help_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('help_name', models.CharField(max_length=255)),
        #     ],
        #     options={
        #         'db_table': 'need_help',
        #     },
        # ),
        migrations.CreateModel(
            name='ServicesOffered',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('services', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'services_offered',
            },
        ),
        migrations.CreateModel(
            name='SystemLanguage',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'system_language',
            },
        ),
    ]
