# Generated by Django 5.2.7 on 2025-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredac_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageOptions',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('languages_known', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'language_options',
            },
        ),
    ]
