# Generated by Django 5.2.7 on 2025-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caredac_admin', '0002_languageoptions'),
        ('caredac_admin', '0002_needhelp'),
    ]

    operations = [
    ]
