# Generated by Django 5.2.7 on 2025-12-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caredac_admin', '0002_needhelp'),
        ('caregiver', '0001_initial'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hindi', 'Hindi'), ('french', 'French'), ('english', 'English')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'caregiver_languages',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('comfort_with_pets', 'Comfort with Pets'), ('has_own_transport', 'Has Own Transport'), ('non_smoker', 'Non-Smoker')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'caregiver_preferences',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cr_training', 'CR Training'), ('first_aid_training', 'First Aid Training'), ('special_need_care', 'Special Need Care')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'caregiver_skills',
            },
        ),
        migrations.CreateModel(
            name='CaregiverAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('child_count', models.PositiveIntegerField()),
                ('child_age_service', models.CharField(blank=True, max_length=255, null=True)),
                ('time_offering', models.IntegerField(choices=[(0, 'Part-Time'), (1, 'Full-Time')])),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='caregiver.caregiverinfo')),
                ('services_offering', models.ManyToManyField(blank=True, related_name='availability_services', to='caredac_admin.servicesoffered')),
                ('languages_known', models.ManyToManyField(blank=True, related_name='availability_languages', to='communication.language')),
                ('preferences_accepted', models.ManyToManyField(blank=True, related_name='availability_preferences', to='communication.preference')),
                ('skills', models.ManyToManyField(blank=True, related_name='availability_skills', to='communication.skill')),
            ],
            options={
                'db_table': 'caregiver_availability',
            },
        ),
    ]
